### ISSUE TITLE
UVCH BROWSER Unable to access

### ISSUE THREAD

**Issue by hideoutbush** [hcabel/UnrealVsCodeHelper#6] opened 2023-12-21 06:03 UTC
hello,I'm try to use ctrl+F1 key operation visit the Unreal official documentation,but Plugins gave me a mistake,As shown in the following picture
![微信截图_20231221140251](https://github.com/hcabel/UnrealVsCodeHelper/assets/93957385/074f7395-2736-4940-b736-793647d69511)

**Comment by hcabel** [comment] 2024-03-16 23:57
Thanks for reporting, I'll close it for being a duplicate of [issue5](https://github.com/hcabel/UnrealVsCodeHelper/issues/5) and fix it soon

**Closed as completed by hcabel** 2024-03-16 23:57 UTC
Labels: duplicate
